// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpcproject.proto

package ie.tosproject.grpcproject;

public interface LoginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tosproject.LoginRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string firstname = 1;</code>
   */
  java.lang.String getFirstname();
  /**
   * <code>string firstname = 1;</code>
   */
  com.google.protobuf.ByteString
      getFirstnameBytes();

  /**
   * <code>string lastname = 2;</code>
   */
  java.lang.String getLastname();
  /**
   * <code>string lastname = 2;</code>
   */
  com.google.protobuf.ByteString
      getLastnameBytes();

  /**
   * <code>int32 membershipNumber = 3;</code>
   */
  int getMembershipNumber();
}
