// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ambulance.proto

package com.tosproject.grpcenterprise;

public interface AddressRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AddressRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string addressquestion = 1;</code>
   */
  java.lang.String getAddressquestion();
  /**
   * <code>string addressquestion = 1;</code>
   */
  com.google.protobuf.ByteString
      getAddressquestionBytes();
}
