// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ambulance.proto

package com.tosproject.grpcenterprise;

public interface AddressResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AddressResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string addressconfirm = 1;</code>
   */
  java.lang.String getAddressconfirm();
  /**
   * <code>string addressconfirm = 1;</code>
   */
  com.google.protobuf.ByteString
      getAddressconfirmBytes();
}
