// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ambulance.proto

package com.tosproject.grpcenterprise;

public interface AmbulanceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AmbulanceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ambulancequestion = 1;</code>
   */
  java.lang.String getAmbulancequestion();
  /**
   * <code>string ambulancequestion = 1;</code>
   */
  com.google.protobuf.ByteString
      getAmbulancequestionBytes();
}
