// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ambulance.proto

package com.tosproject.grpcenterprise;

public final class Ambulance {
  private Ambulance() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AmbulanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AmbulanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConfirmResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConfirmResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddressRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddressRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddressResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddressResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017ambulance.proto\"-\n\020AmbulanceRequest\022\031\n" +
      "\021ambulancequestion\030\001 \001(\t\"+\n\017ConfirmRespo" +
      "nse\022\030\n\020confirmambulance\030\001 \001(\t\")\n\016Address" +
      "Request\022\027\n\017addressquestion\030\001 \001(\t\")\n\017Addr" +
      "essResponse\022\026\n\016addressconfirm\030\001 \001(\t2v\n\020A" +
      "mbulanceService\0222\n\tambulance\022\021.Ambulance" +
      "Request\032\020.ConfirmResponse\"\000\022.\n\007address\022\017" +
      ".AddressRequest\032\020.AddressResponse\"\000B!\n\035c" +
      "om.tosproject.grpcenterpriseP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_AmbulanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AmbulanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AmbulanceRequest_descriptor,
        new java.lang.String[] { "Ambulancequestion", });
    internal_static_ConfirmResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ConfirmResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConfirmResponse_descriptor,
        new java.lang.String[] { "Confirmambulance", });
    internal_static_AddressRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_AddressRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddressRequest_descriptor,
        new java.lang.String[] { "Addressquestion", });
    internal_static_AddressResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_AddressResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddressResponse_descriptor,
        new java.lang.String[] { "Addressconfirm", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
