// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ambulance.proto

package com.tosproject.grpcenterprise;

public interface ConfirmResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ConfirmResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string confirmambulance = 1;</code>
   */
  java.lang.String getConfirmambulance();
  /**
   * <code>string confirmambulance = 1;</code>
   */
  com.google.protobuf.ByteString
      getConfirmambulanceBytes();
}
