// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: deploy.proto

package com.tosproject.grpcenterprise;

public interface LongDeployRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tosproject.LongDeployRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
