// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: deploy.proto

package com.tosproject.grpcenterprise;

public interface LongDeployResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tosproject.LongDeployResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string result = 1;</code>
   */
  java.lang.String getResult();
  /**
   * <code>string result = 1;</code>
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
